### ISSUE TITLE
NSArray & NSDictionary

### ISSUE THREAD

**Issue by mythodeia** [christopherney/SQPersist#3]
First of all thanks for open sourcing your library. 

I have a question regarding the properties an SQPObject can accept.
Lets say a User model has a property called albums which is an array.
Now this array is actually an array of id's of the album model.
Since the array is not in the list of compatible types will it be saved as something else or not at all?
Is this scenario the same for nsdictionaries?

thanks again

**Comment by JonathanVanhumbeeck** [comment]
Hi mythodeia,

I'm currently facing to the same problem, I've an Array of models linked to the parent with an Array of ids.

I succeeded to save my array of models in the database with the right model and the right id but the parent is not updated.

So I'm not able to fetch the array model from the parent object.

Did you find a solution ?

**Comment by mythodeia** [comment]
Hello Jonathan,

I ended up saving just ids and not the whole objects as time was of the
essence.
Are you using the saveentitywithcascade option in the parent class?

If you find a solution please let me know
Thanks

**Comment by JonathanVanhumbeeck** [comment]
Hi, first I initialize an array with models initialized with the ids.

Example : User -> collection[] -> book[id->0],book[id->1],book[id->2]

Yes, save entity with cascade is working fine, cause my entities book are
saved in the database.
The problem is that the albums array is still empty cause NSArray and
NSMutableArray are considered as not compatible types and so not saved when
the parent is saved

Yes I'll let you know

2015-08-18 11:02 GMT+02:00 Konstantinos K. <notifications@github.com>:

> Hello Jonathan,
>
> I ended up saving just ids and not the whole objects as time was of the
> essence.
> Are you using the saveentitywithcascade option in the parent class?
>
> If you find a solution please let me know
> Thanks
>
> On Τρί, 18 Αυγ 2015 at 11:46 JonathanVanhumbeeck <notifications@github.com
> >
> wrote:
>
> > Hi mythodeia,
> >
> > I'm currently facing to the same problem, I've an Array of models linked
> > to the parent with an Array of ids.
> >
> > I succeeded to save my array of models in the database with the right
> > model and the right id but the parent is not updated.
> >
> > So I'm not able to fetch the array model from the parent object.
> >
> > Did you find a solution ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/christopherney/SQPersist/issues/3#issuecomment-132122070
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christopherney/SQPersist/issues/3#issuecomment-132125873>
> .
>



-- 

[image:
https://ci4.googleusercontent.com/proxy/1LrkVgsFmWfddHBzqXISTMxvCCS2YxdwtVUdZQql0xlg0hdYXhr0OD92py5XrZbQu-QaVxi4QIngZzFlpe7eoEWJ3J9ZvR2XvOOrAR7p0TH68S8=s0-d-e1-ft#http://www.bhc.be/sites/default/files/signatures/2014/image002.png]
<http://www.bhc.be/fr>
*Jonathan Vanhumbeeck* |
*Software Engineer - Mobile Developper*

Tél: +32 65 33 69 00

Email: jonathan.vanhumbeeck@bhc.be
<https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=guillaume.leclercq@bhc.be>

http://www.bhc.be/



[image:
https://ci5.googleusercontent.com/proxy/FtF3sP0gCGlWpXVEFu3qzZ6k-pB9Dw50NmnNrUUUt-GrBip4RGoCSXI6OlC8ghAFvsIQNiEpVPFMzaw_Dlw4Y1fXUeXg-beyuQFDWAKVt_9spKQ=s0-d-e1-ft#http://www.bhc.be/sites/default/files/signatures/2014/image004.png]
<https://twitter.com/BHCsprl>

[image:
https://ci4.googleusercontent.com/proxy/uHNzmO-pxePS6Q6MMzwpYPWD_rkK8mHMb7SCkaude3GrI7_6KnXyTJuy0GxEDNbOIjtJyRRG0mEZZy3JnUz0vxYOIarFL6bABLjrTiOGLCh-nMQ=s0-d-e1-ft#http://www.bhc.be/sites/default/files/signatures/2014/image006.png]
<https://www.facebook.com/pages/BHC/119983618066687>

[image:
https://ci6.googleusercontent.com/proxy/XDStOu70eQG8qt2-9nZHXzRZ3e9fPJEgS9OUlqjzy33BkZmxO0-UJtHPNGKUJeAJnnbFDw7q3GonIl0GTf5ZXpgRESV-caGP6vOlvfdCC_77dG0=s0-d-e1-ft#http://www.bhc.be/sites/default/files/signatures/image008.png]
<http://www.linkedin.com/company/bhc>

[image:
https://ci6.googleusercontent.com/proxy/ZYNjC15HZWCy6j2V8EvVvnES5FRURGejVBeh1cQoCTzbQhKRRUnbENBKoG80rkK1qgusfCAAtimvI-5qRuhyj-0OwRF7s67cuvlUCEpJGg8PeeY=s0-d-e1-ft#http://www.bhc.be/sites/default/files/signatures/image010.png]
<http://www.2015entreprises.eu/>

<http://www.bhc.be/fr/openerp>
